### ISSUE TITLE
Request: passing webcam to video device.

### ISSUE THREAD

**Issue by joe-eis** [Mazhar004/MODNet_BGRemover#13]
Thank you for the good work. It gives excellent results when cropping heads, even with curly hair.

But unfortunately the result cannot be used as a device with the webcam option. It would be nice if such an output would be added to the script. 

Unfortunately, I have no idea about programming, but I imagine to forward the signal to v4linux or OBS.

**Comment by Mazhar004** [comment]
I think you mean to say, external device as a webcam.
- You can chnage the number, and I think it will work. **0->1**
- https://github.com/Mazhar004/MODNet-BGRemover/blob/75d30850430b506776ce3f4774d209ef2064ffdf/bg_remove.py#L197
